### ISSUE TITLE
software license?

### ISSUE THREAD

**Issue by taylorreiter** [fteufel/DeepPeptide#1]
Hello! I am interested in trying DeepPeptide in my work and saw that there is no license in the GitHub repo. I didn't see one in the publication or on the web server, but I apologize if I missed it! Would you be willing to add a license so re-use terms are clear? Thank you for your consideration!

**Comment by fteufel** [comment]
Hi @taylorreiter thanks for asking - completely forgot. I've added the BSD license now.
