### ISSUE TITLE
TypeError when using predictor.py's argument --batch_size 

### ISSUE THREAD

**Issue by taylorreiter** [fteufel/DeepPeptide#2]
Hello, thank you for creating such a wonderful tool! In preliminary runs I've been excited by the outputs of DeepPeptide. It ran perfectly when I used
```
python3 predict.py -ff sequences.pep -od testrun_outputs/
```

For larger runs (300k proteins), I noticed it was fairly slow (>12 hours to complete 5%) so tried to increase the batch size:
```
python3 predict.py -ff sequences.pep -od testrun_outputs/ --batch_size 1000
```

This produced the following error:
```
Traceback (most recent call last):
  File "/Users/taylorreiter/github/DeepPeptide/predictor/predict.py", line 203, in <module>
    main()
  File "/Users/taylorreiter/github/DeepPeptide/predictor/predict.py", line 90, in main
    batches = utils.batchify_sequences(seqs, args.batch_size)
  File "/Users/taylorreiter/github/DeepPeptide/predictor/utils.py", line 254, in batchify_sequences
    batch_sequences = sequences[b_start:b_end]
TypeError: slice indices must be integers or None or have an __index__ method
```

Wrapping line 90 of predict.py with `int()` fixed the problem:
https://github.com/fteufel/DeepPeptide/blob/main/predictor/predict.py#L90
```
batches = utils.batchify_sequences(seqs, int(args.batch_size))
```

**Comment by fteufel** [comment]
Thank you for the kind words!

Yes, this was misconfigured as `str`. I've changed it now to be parsed as `int`.

Maybe the batch size will speed up processing, but I don't have experience at the 300k protein scale. I would probably split the input and submit that as multiple smaller jobs.

**Comment by taylorreiter** [comment]
Thank you for the recommendation! I'll try going that route if the batch size isn't performant.
