### ISSUE TITLE
UnboundLocalError: local variable 'marginal_dict' referenced before assignment with argument -of json

### ISSUE THREAD

**Issue by taylorreiter** [fteufel/DeepPeptide#3]
Hello again! I recently added `-of json` to my DeepPeptide `predict.py` command and received the following error:

```
Writing JSON in interactive_testrun_outputs
Traceback (most recent call last):
  File "predict.py", line 218, in <module>
    main()
  File "predict.py", line 212, in main
    json.dump(marginal_dict, open(os.path.join(args.output_dir, 'sequence_outputs.json'), 'w'), indent=1)
UnboundLocalError: local variable 'marginal_dict' referenced before assignment
```

`marginal_dict` is defined in line 172 of `predict.py`, but only if `img` is the output format.
https://github.com/fteufel/DeepPeptide/blob/main/predictor/predict.py#L172

however, `marginal_dict` is referenced in line 197 regardless of output format (`img` or `json`)
https://github.com/fteufel/DeepPeptide/blob/main/predictor/predict.py#L197

**Comment by fteufel** [comment]
Oops - looks like i've never actually tested the json only mode in this codebase. Made some fixes and just tested it, should work now.
